# DreamShell ##version##
# (с) 2008-2014 SWAT
# http://www.dc-swat.ru
# 

KOS_CFLAGS += -I./ -I../../include -I../../include/SDL -DHAVE_SDL_TTF

TARGET = ../libSDL_rtf_0.1.1.a
OBJS = 	rtfactn.o rtfreadr.o SDL_rtfreadr.o SDL_rtf.o

include ../../sdk/Makefile.library
