# Makefile created by SWAT
# http://www.dc-swat.ru

TARGET = libSDL_gui.a

KOS_CPPFLAGS += -fno-operator-names -fno-rtti -fno-exceptions

OBJS =	\
    SDL_gui.o Exception.o Object.o Surface.o Font.o Callback.o \
	Drawable.o Screen.o Widget.o Container.o \
	FastFont.o TrueTypeFont.o \
	Layout.o Panel.o CardStack.o \
	FastLabel.o Label.o Picture.o TextEntry.o \
	AbstractButton.o Button.o ToggleButton.o \
	ProgressBar.o ScrollBar.o \
	AbstractTable.o ListBox.o \
	VBoxLayout.o RealScreen.o \
	ScrollPanel.o Window.o \
	RTF.o FileManager.o Dialog.o


KOS_CFLAGS += -I../../include/SDL -I../include -I../../include

include $(KOS_BASE)/ds/lib/Makefile.prefab
