# DreamShell ##version##
# by SWAT
# libtolua++ Makefile

TARGET = libtolua++.a
OBJS = src/lib/tolua_event.o src/lib/tolua_is.o src/lib/tolua_map.o \
	src/lib/tolua_push.o src/lib/tolua_to.o

KOS_CFLAGS += -I./include -I../../../include -I../../../include/lua -I./src/lib

include ../../../lib/Makefile.prefab
