# Makefile for creating distribution
# Type 'make dist' for create tar-gziped archiv. 

#
# Author: Lubomir Host 'rajo' <rajo AT platon.sk>
#

# $Platon: libcfg+/doc/sgml/Makefile,v 1.4 2003/04/15 23:16:44 rajo Exp $

all:
	cd .. \
	&& $(MAKE)
