# KallistiOS Ogg/Vorbis Decoder Library
#
# Library Makefile
# (c)2001 Thorsten Titze
# Based on KOS Makefiles by Dan Potter

SUBDIRS= src

all:	subdirs
clean:
	-rm -rf build/*.o build/*.a src/*.o src/*.a

include $(KOS_BASE)/Makefile.rules

