#
# DreamShell ISO Loader
# GD-ROM/CD-ROM (SPI/ATAPI)
# (c) 2009-2020 SWAT
#

include Makefile.cfg

TARGETCFLAGS += $(CD_CFLAGS)
LOBJECTS += $(CD)

all: rm-elf $(BUILD)/cd.bin

rm-elf:
	rm -f $(LOBJECTS) $(BUILD)/cd.bin $(BUILD)/cd.elf

$(BUILD)/cd.elf: $(LOBJECTS)
	$(TARGETCC) $(TARGETCFLAGS) $(TARGETLDFLAGS) -o $@ $(LOBJECTS) $(LIBS)
	$(TARGETSIZE) $@
