#
# DreamShell ISO Loader
# Network
# (c) 2009-2020 SWAT
#

include Makefile.cfg

TARGETCFLAGS += $(DCL_CFLAGS)
LOBJECTS += $(NET)

all: rm-elf $(BUILD)/net.bin

rm-elf:
	rm -f $(LOBJECTS) $(BUILD)/net.bin $(BUILD)/net.elf

$(BUILD)/net.elf: $(LOBJECTS)
	$(TARGETCC) $(TARGETCFLAGS) $(TARGETLDFLAGS) -o $@ $(LOBJECTS) $(LIBS)
	$(TARGETSIZE) $@
