#
# DreamShell ISO Loader
# SD Card
# (c) 2009-2020 SWAT
#

include Makefile.cfg

TARGETCFLAGS += $(SD_CFLAGS)
LOBJECTS += $(SD)

all: rm-elf $(BUILD)/sd.bin

rm-elf:
	rm -f $(LOBJECTS) $(BUILD)/sd.bin $(BUILD)/sd.elf

$(BUILD)/sd.elf: $(LOBJECTS)
	$(TARGETCC) $(TARGETCFLAGS) $(TARGETLDFLAGS) -o $@ $(LOBJECTS) $(LIBS)
	$(TARGETSIZE) $@
