#
# DreamShell ISO Loader
# SD Card
# (c) 2009-2025 SWAT
#

include Makefile.cfg

TARGETCFLAGS += $(SD_CFLAGS)
LOBJECTS += $(SD)

NAME ?= sd

all: $(BUILD)/$(NAME).bin

$(BUILD)/$(NAME).elf: $(OBJECTS)
	$(TARGETCC) $(TARGETCFLAGS) $(TARGETLDFLAGS) -o $@ $(OBJECTS) $(LIBS)
	$(TARGETSIZE) $@
