#
# DreamShell ISO Loader
# GD-ROM/CD-ROM (SPI/ATAPI)
# (c) 2009-2025 SWAT
#

include Makefile.cfg

TARGETCFLAGS += $(CD_CFLAGS)
LOBJECTS += $(CD)

NAME ?= cd

all: $(BUILD)/$(NAME).bin

$(BUILD)/$(NAME).elf: $(OBJECTS)
	$(TARGETCC) $(TARGETCFLAGS) $(TARGETLDFLAGS) -o $@ $(OBJECTS) $(LIBS)
	$(TARGETSIZE) $@
