#
# DreamShell ISO Loader
# G1-ATA (IDE)
# (c) 2009-2020 SWAT
#

include Makefile.cfg

TARGETCFLAGS += $(IDE_CFLAGS)
LOBJECTS += $(IDE)

all: rm-elf $(BUILD)/ide.bin

rm-elf:
	rm -f $(LOBJECTS) $(BUILD)/ide.bin $(BUILD)/ide.elf

$(BUILD)/ide.elf: $(LOBJECTS)
	$(TARGETCC) $(TARGETCFLAGS) $(TARGETLDFLAGS) -o $@ $(LOBJECTS) $(LIBS)
	$(TARGETSIZE) $@
