#
# DreamShell ISO Loader
# G1-ATA (IDE)
# (c) 2009-2025 SWAT
#

include Makefile.cfg

TARGETCFLAGS += $(IDE_CFLAGS)
LOBJECTS += $(IDE)

NAME ?= ide

all: $(BUILD)/$(NAME).bin

$(BUILD)/$(NAME).elf: $(OBJECTS)
	$(TARGETCC) $(TARGETCFLAGS) $(TARGETLDFLAGS) -o $@ $(OBJECTS) $(LIBS)
	$(TARGETSIZE) $@
