# Makefile created by SWAT
# http://www.dc-swat.ru

TARGET = libSDL_Console.a

OBJS = 	SDL_console.o DT_drawtext.o internal.o

KOS_CFLAGS += -I$(KOS_BASE)/../kos-ports/include/SDL -I../include -DHAVE_SDLIMAGE

include ../../Makefile.prefab
