# DreamShell ##version##
# (с) 2008-2014 SWAT
# http://www.dc-swat.ru
# 

KOS_CFLAGS += -I./ -I../../include -I../../include/SDL

TARGET = libSDL_ttf_2.0.11.a

OBJS = SDL_ttf.o

include ../../sdk/Makefile.library
