# KallistiOS Ogg/Vorbis Decoder Library
#
# Library Makefile
# (c)2001 Thorsten Titze
# Based on KOS Makefiles by Dan Potter

SUBDIRS= lib

all: subdirs

clean:
	-rm -rf build/*.o build/*.a lib/*.o lib/*.a

include $(KOS_BASE)/Makefile.rules

