# Parallax for DreamShell ##version##
#
# Makefile
# (c)2002 Dan Potter
# (c)2014 SWAT

TARGET = libparallax.a
OBJS := $(patsubst %.c,%.o,$(wildcard src/*.c))

KOS_CFLAGS += -I../../include

# Grab the shared Makefile pieces
include ../../sdk/Makefile.library

