# KallistiOS ##version##
#
# libmp3 Makefile

TARGET = libmp3_mpg123.a
OBJS =
LIB_OBJS = build/*.o
#SUBDIRS = xingmp3 libmp3
LOCAL_CLEAN = build/*.o build/*.a
SUBDIRS = mpg123 libmp3
#KOS_CFLAGS += -DNOANALYSIS

include ../../../sdk/Makefile.library
